@base_url = http://localhost:3000/api
@token = dG_wVzcFu0Gn5Iu5R1QXhz0_G-wcudvWUw7fxcYoJFMi

### test api ###
GET {{base_url}}


### login ###
POST {{base_url}}/auth/login
Content-Type: application/json

{
    "email": "jose.acevesgon@gmail.com"
}

### authenticate ###
GET {{base_url}}/auth/authenticate?stytch_token_type=magic_links&token={{token}}

### logout ###
POST {{base_url}}/auth/logout

### validate mail ###
POST {{base_url}}/analyze-mail/validate

