@base_url = http://localhost:3000/api
@token = 
@mail = 
@password = 
@api_key = 
@mailId = 
### test api ###
GET {{base_url}}

### sign up ###
POST {{base_url}}/auth/signup
Content-Type: application/json

{
    "email": "{{mail}}",
    "type": "password_login",
    "password": "{{password}}"
}

### login magic link ###
POST {{base_url}}/auth/login
Content-Type: application/json

{
    "email": "{{mail}}",
    "type": "magic_links"
}

### login password login ###
POST {{base_url}}/auth/login
Content-Type: application/json

{
    "email": "{{mail}}",
    "type": "password_login",
    "password": "{{password}}"
}

### reset password ###
POST {{base_url}}/auth/reset-password
Content-Type: application/json

{
    "email": "{{mail}}"
}

### authenticate magic link ###
POST {{base_url}}/auth/authenticate?stytch_token_type=magic_links&token={{token}}

### authenticate login ###
POST {{base_url}}/auth/authenticate?stytch_token_type=login&token={{token}}

### authenticate password reset ###
POST {{base_url}}/auth/authenticate?stytch_token_type=reset_password&token={{token}}
Content-Type: application/json

{
    "password": "{{password}}"
}

### status ###
GET {{base_url}}/auth/status


### logout ###
POST {{base_url}}/auth/logout

### logout all ###
POST {{base_url}}/auth/logout-all

### change trial ###
POST {{base_url}}/auth/change-trial
Content-Type: application/json

{
    "api_key": "{{api_key}}"
}

### validate mail ###
POST {{base_url}}/analyze-mail/validate
Content-Type: multipart/form-data; boundary=validate-boundary

--validate-boundary
Content-Disposition: form-data; name="emlFile"; filename="test2.eml"
Content-Type: message/rfc822

< ./test2.eml
--validate-boundary--

### history ###
GET {{base_url}}/analyze-mail

### get by id ###
GET {{base_url}}/analyze-mail/{{mailId}}

### delete ###
DELETE {{base_url}}/analyze-mail/{{mailId}}
